### ISSUE TITLE
Immediate crash on TS3 3.3.0 with TokoVoIP 1_2_2 on Windows 10 Pro 1803

### ISSUE THREAD

**Issue by Aklaba** [Itokoyamato/TokoVOIP_TS3#16]
Numerous re-installs, restarts and file relocations have proved unsuccessful. TS3 installs and opens just fine, upon installation of TokoVoIP 1_2_2, TS3 crashes immediately upon launch. Once any trace of Toko is removed, TS3 opens fine once again.

Crashes were present in these situations:

Teamspeak3 3.3.0 both 32 bit and 64 bit using Toko 1_2_2
Teamspeak3 3.2.5 both 32 bit and 64 bit using Toko 1_2_1_3

Attached is most recent crash dump from TS3 3.3.0 64 bit with Toko 1_2_2

[ts3dump_1561637942895.zip](https://github.com/Itokoyamato/TokoVOIP_TS3/files/3334716/ts3dump_1561637942895.zip)

Contact @Aklaba#2703 on Discord for more information if necessary.

**Comment by Shayeno2Tone** [comment]
I am also having the same issue with I believe the exact same problem as you. 

[ts3client_2019-06-27__18_39_55.315641.log](https://github.com/Itokoyamato/TokoVOIP_TS3/files/3336059/ts3client_2019-06-27__18_39_55.315641.log)

Any help would be appreciated.

**Comment by Itokoyamato** [comment]
I have identified the issue. Working on fixing it.

**Comment by Itokoyamato** [comment]
Well, that's a funny one. Turns out it's not an issue with windows itself, but with Razer Chroma. They have decided to start using the port 1337 in their recent update, which happens to be the same port TokoVOIP uses.

For a temporary fix, you can go in your task manager and kill the process `RzSDKServer.exe`

I will be changing the port used by TokoVOIP as soon as I can, but both players and servers will be required to update the plugin and script to apply this change once it's available.

**Comment by Itokoyamato** [comment]
Fixed in #15
