### ISSUE TITLE
TS name

### ISSUE THREAD

**Issue by korathias** [Itokoyamato/TokoVOIP_TS3#19]
For the life of me I can not figure out what to enter into this line to get the in game name showing in TS:

I have tried this: 

localName = "[" .. GetPlayerName(playerList()) .. "] ", -- If set, this name will be used as the user's Teamspeak display name

I have also tried to just set it to local as well.

**Comment by Itokoyamato** [comment]
Its already setting the ingame name as the TS name by default. You need to do it after the script started tho (like it's done by default), otherwise fivem will not return the correct name when a player joins.
[Here](https://github.com/Itokoyamato/TokoVOIP_TS3/blob/master/fivem_script/tokovoip_script/c_config.lua#L53)

**Comment by korathias** [comment]
OK because I am using kashacters as well so there is a delay before the character from the DB is chosen. Can I put in a delay on the startup so it can then pull the right name?

**Comment by Itokoyamato** [comment]
You can update the localName at any time, doesnt matter if you put a delay before it

**Comment by korathias** [comment]
Ok thank you.
