### ISSUE TITLE
Some people can hear everybody

### ISSUE THREAD

**Issue by johnnypernik** [Itokoyamato/TokoVOIP_TS3#24]
Few random people hear everybody at server :(

**Comment by shredxt** [comment]
Are they running teamspeak as Administrator?

**Comment by Itokoyamato** [comment]
That's too little information to do anything with it. Hopefully the upcoming PR #25 sovles your issues. Otherwise I'll need more to go on and figure out this issue.

**Comment by zbadrabbit** [comment]
We have this occur once in awhile as well. Usually I tell them to go back to the lobby channel and let the script move them back. This does seem to solve it for most people though some have to restart the game and TS to get it resolved. I cannot pin down a single solid reproduction event sadly.

**Comment by Itokoyamato** [comment]
I applied a fix for an issue that could lead to the script not initializing properly in some cases.
It's available in [v1.3.4](https://github.com/Itokoyamato/TokoVOIP_TS3/releases). Please try it out and tell me if your issue still happens.

**Comment by duckhunter392** [comment]
@Itokoyamato I believe the issue people are having with this is the in game voice is still enabled. So if someone has the default voice chat enabled then they can hear other people who also have it enabled. Had this issue recently but it was fixed by disabling the in game voice. I'll write up a PR when I have a minute or two.
