### ISSUE TITLE
"Hear everyone issue" how to fix it

### ISSUE THREAD

**Issue by PichotM** [Itokoyamato/TokoVOIP_TS3#27]
Hello, it seems that users that are not included in the lua users table and join the channel after you will not be muted until you are told to do so.

It means that the plugin should mute automatically ALL PEOPLE that join the channel to be certain that they will be unmuted only if needed

**Comment by DistinctMatriarch** [comment]
Got the same issue they need to update the mod

**Comment by SaraBeheshti** [comment]
still we have this problem, people should join radio channel and press caps lock one time then he got muted and everything is fine. 
and another problem is that toko voip does not work until i start other voice stuff (like gamz-voice) and stop it one time. (i think this problem is no global but i have this issue)

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and does mute everyone by defaults
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
