### ISSUE TITLE
Script Erro 

### ISSUE THREAD

**Issue by LucasR0cha** [Itokoyamato/TokoVOIP_TS3#43]
Hello Dylan, again I came here to report a problem that still persists even with the new version.
After a while this error starts on the console and then players stop listening to some in the game and others can perfectly hear the person the other player may not be able to hear.
only returns to normal when I force a manual restart in the console script

![image](https://user-images.githubusercontent.com/16357292/61740182-5f606b00-ad64-11e9-8de9-326d27d6ce4b.png)

**Comment by shredxt** [comment]
Yes, we are having the same error with a select few people being unable to hear any other players. I also noticed the "unmute all" option is missing from the "Plugins" dropdown, although this may be an intentional change.

**Comment by Itokoyamato** [comment]
I thought I fixed that c_util issue, but I made typo, oops.
Fixed it in [v1.3.4](https://github.com/Itokoyamato/TokoVOIP_TS3/releases)
Please tell me if that solves your issues.

Also, it was not intentional to remove 'unmute all' from the plugin, I just forgot to add it back when I update RadioFX. I'll try to add it back in the next plugin update.
