### ISSUE TITLE
Ingame Tokovoip_script popup Problem

### ISSUE THREAD

**Issue by durwildchild** [Itokoyamato/TokoVOIP_TS3#64]
Hey guys can i disable this Popup ?
![dddddd](https://user-images.githubusercontent.com/57397643/68205307-42c20900-ffca-11e9-9ff5-380054ae889d.png)

**Comment by rex2630** [comment]
You have really slow pc or server

**Comment by nicktrick92** [comment]
> Hey guys can i disable this Popup ?
> ![dddddd](https://user-images.githubusercontent.com/57397643/68205307-42c20900-ffca-11e9-9ff5-380054ae889d.png)

The resource time warnings is through FiveM and is unable to be removed without fixing the issue that is present. What that indicates is that the script (TokoVoip in this case) is utilizing too much CPU processing power and is causing frame drops. This is likely either due to something you added to the script after the fact (Additional loops, calculations, etc.) or a slow client/server, as was mentioned above. You should look at fixing that instead of trying to disable the box since it's a real issue.
