### ISSUE TITLE
tokovoip stop working  when players +72

### ISSUE THREAD

**Issue by achrafhammani** [Itokoyamato/TokoVOIP_TS3#93]

**Comment by achrafhammani** [comment]
![20200312224520_1](https://user-images.githubusercontent.com/62339546/79076458-2b621700-7cf2-11ea-90df-16fdba1edd03.jpg)

**Comment by Poggicek** [comment]
You gave him no information whats so ever, he is not able to help you.

**Comment by achrafhammani** [comment]
what do you need information

**Comment by LeandroTiim** [comment]
Achrafhammani, Were you able to solve this problem? 
I'm going through the same situation, please help me!

**Comment by Itokoyamato** [comment]
Since no information has been provided, i'll consider this as stale.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases)
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
